FROM debian:stretch

RUN  apt update && \
     apt install -y --no-install-recommends \
        cmake \
        dietlibc-dev \
        gcc \
        gdb \
        libc-dev \
        libgcc-6-dev \
        libowfat-dietlibc-dev \
        make ustat.diet


